### ISSUE TITLE
When clicking on home button its throwing error, I want the functionality like Google maps, like when you click home button it shows the smaller map

### ISSUE THREAD

**Issue by alemantrix-settyl** [wrbl606/floating#1]
![image](https://user-images.githubusercontent.com/111136956/201374822-d98d912e-ea88-4d1a-81fb-4b6861266603.png)

**Comment by wrbl606** [comment]
What's the code that triggers the floating package?

**Comment by alemantrix-settyl** [comment]
![image](https://user-images.githubusercontent.com/111136956/201387733-1198184f-a37f-41bb-a3f7-8bfb90bbc8cb.png)
pls help! I want to use it when the app goes into the pause or inactive state...

**Comment by wrbl606** [comment]
You have to enable floating when the app state switches to .inactive. .paused event is called too late to do this, as stated in the exception.

It's implemented in the example app:
![image](https://user-images.githubusercontent.com/15102395/201398106-8c891064-e97a-48d9-9788-b28ed54631fc.jpeg)

**Comment by wrbl606** [comment]
You have to enable floating when the app state switches to .inactive. .paused event is called too late to do this, as stated in the exception.

It's implemented in the example app:
![image](https://user-images.githubusercontent.com/15102395/201398106-8c891064-e97a-48d9-9788-b28ed54631fc.jpeg)

**Comment by wrbl606** [comment]
Does it work as expected after proposed changes?

**Comment by alemantrix-settyl** [comment]
I can't believe in my spectacles, its working as expected,,,Thank you so so much man, you made my day 🙏
