### ISSUE TITLE
Resume current state error

### ISSUE THREAD

**Issue by xOldeVx** [wrbl606/floating#12]
I have a video player, i want to continue the video when i minimize the app, but the state is changed when minimize and the `videoPlayer()` widget is rebuild and the video is restart, how can i fix it?

```
PiPSwitcher(
      childWhenEnabled: videoPlayer(),
      childWhenDisabled: Scaffold(body: Column(
      children: [
            videoPlayer(),
            videoList(),
      ],
    ),
);
```

**Comment by wrbl606** [comment]
See https://github.com/wrbl606/floating/issues/2
