### ISSUE TITLE
dispose doesn't work

### ISSUE THREAD

**Issue by Mae623** [wrbl606/floating#15]
Hello, I use floating in a specific page. When the page dispose, I execute floating.dispose() too. But
 I will find the floating window doesn't closed, it still show on my phone.
Is there any advice?
Thank you very much.

**Comment by wrbl606** [comment]
Calling .dispose() on a Floating instance frees up resources used for PiP state polling. There is no programmatic way to disable PiP mode, it only happens on user demand.

**Comment by Mae623** [comment]
> 

Thank your for your answer！
