### ISSUE TITLE
Exit Picture in picture mode

### ISSUE THREAD

**Issue by long2602** [wrbl606/floating#16]
Hi Wrbl606,

How to disable/ exit picture in picure mode. I see function enable() -> call this fun to enable pip mode. How to disable mode pip?

thanks

**Comment by kamal614** [comment]
Having the same issue, how can we do that? Did anyone found the solution

**Comment by kamal614** [comment]
Hey @long2602 did you found any solution for this?

**Comment by wrbl606** [comment]
PiP mode can only be disabled via user action on the PiP window itself, there's no API available to do this programmatically.
