### ISSUE TITLE
How to avoid re-rendering of widgets when it switches to PiP mode and vice-versa?

### ISSUE THREAD

**Issue by AryanKuAg** [wrbl606/floating#2]
![image](https://user-images.githubusercontent.com/61811630/204051549-7ead3218-de48-4826-8e11-0b9668d15c01.png)
Actually the code you see here is rendering a map.
![image](https://user-images.githubusercontent.com/61811630/204051643-57bedb4e-0c7f-473e-97e1-4e8d173fe0a6.png)
This Widget HereMap() and its functional argument _onMapCreated is very computational expensive, when I switches to PiP mode then childWhenEnabled is called and its re-rending the entire widget (A lot of computations). Can we somehow make it static or something? Just wanna avoid the re-rendering part, Pls help!!!

**Comment by wrbl606** [comment]
It'll be a great case to use `GlobalKey` in. Global key will make clear for Flutter that those two map widgets are actually the same and shouldn't be rerendered after `PiPSwitcher` detects the app mode change. [Here's a great article](https://medium.com/flutter/keys-what-are-they-good-for-13cb51742e7d) about keys.

**Comment by tushar-appyhigh** [comment]
@AryanKuAg can you post the solution if it is solved for you cause I'm also trying to achieve same solution with here maps.
