### ISSUE TITLE
The console displays too many logs

### ISSUE THREAD

**Issue by yoer** [wrbl606/floating#28]
![image](https://github.com/user-attachments/assets/d0141e18-bf3a-47f5-8b28-50b08e869c42)

Because **pipStatusStream** is referenced in **PiPSwitcher**, **pipStatusStream** starts a very frequent timer, resulting in frequent access to **activity.packageManager.hasSystemFeature(PackageManager.FEATURE_PICTURE_IN_PICTURE)**, which will keep outputting logs on the console.

The solution is to save the init state when accessing **isPipAvailable**, and return the last queried state the next time you access it.
![image](https://github.com/user-attachments/assets/373d12c9-40f4-436a-ae47-e664fec6d0de)

**Comment by yoer** [comment]
Can it be fixed soon?

**Comment by wrbl606** [comment]
The goal of the frequent access to the API is to provide up to date PiP status, shall it be changed e.g. by a system event, so I don't plan to remove/change it at the moment as it's necessary for the correct behaviour of the plugin.

I tested the package on many devices, both real and emulated, and haven't experienced excessive logs -- might be that your test device is set up with a highly verbose logs output causing the wall of logs. You can also filter out the logs easily, as it has predictable structure to prevent it from distracting you.

**Comment by wrbl606** [comment]
I see the issue, feel free to post a PR with the change that fixes your issue, add this will greatly speed things up.

**Comment by yoer** [comment]
[PR](https://github.com/wrbl606/floating/pull/29) has been submitted

**Comment by wrbl606** [comment]
Fixed in 5.0.1, thanks!
