### ISSUE TITLE
[Proposal] for Event Listener Feature

### ISSUE THREAD

**Issue by Alii-isk** [wrbl606/floating#3]
Just wanted to drop a quick note to say thank you for creating this amazing package. 
I was wondering if there's any chance you could add an event listener to the package? 
like `onPipDisabled` `onPipEnabled`
I think it would be super helpful.

**Thanks again for all your hard work on this, it's greatly appreciated!**

**Comment by wrbl606** [comment]
Every `Floating` instance has a `pipStatus$` stream available to listen to. It's an equivalent for callbacks you proposed, but still, let me know if this is a proper solution for you.

**Comment by wrbl606** [comment]
I'll take the lack of response as a yes and will close this issue. Feel free to open a new one if necessary 🤝

**Comment by Alii-isk** [comment]
Ohh sorry I didn't notice the pipstatus$ stream 
Anyway thank u ,this is definitely working for me
