### ISSUE TITLE
Arguments for PictureInPictureParams

### ISSUE THREAD

**Issue by deckerst** [wrbl606/floating#4]
Thanks for the nice plugin.

Just like the aspect ratio, could you please add arguments when enabling PiP, to be passed to the `PictureInPictureParams` builder? I'm specifically interested in [source rect hint](https://developer.android.com/reference/android/app/PictureInPictureParams.Builder#setSourceRectHint(android.graphics.Rect)).

**Comment by wrbl606** [comment]
Thanks for your message. I would love to have more coverage of the full Android PiP API available 👍 I currently have no plans of implementing this specific setting, but I'm open to contributions. By the looks of it, it shouldn't be too difficult to implement so it'll be a great way to get into the project's contributors list 😀

**Comment by deckerst** [comment]
Working on it. As we're adding arguments to the `enable` method, I think positional arguments don't cut it and should be named arguments instead. However, this is a breaking change. Are you fine with that?

**Comment by wrbl606** [comment]
Sure thing

**Comment by deckerst** [comment]
I opened #5 for you to review. I use the modified plugin internally in my app and it seems to work fine.
